// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPh7JSoMyGuJyUar6mGOOyOwuA31Ld-IY',
    appId: '1:849620310895:web:af6667a639b3db68faa69a',
    messagingSenderId: '849620310895',
    projectId: 'muipzi',
    authDomain: 'muipzi.firebaseapp.com',
    storageBucket: 'muipzi.firebasestorage.app',
    measurementId: 'G-67N56M29RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6JORc9zEIfZ6Xy_v7-ghByc1FBSdEL7c',
    appId: '1:849620310895:android:648f07b1db508971faa69a',
    messagingSenderId: '849620310895',
    projectId: 'muipzi',
    storageBucket: 'muipzi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu4fYJL35nnfdA7K371tujICzUEmpvACc',
    appId: '1:849620310895:ios:e3e9d8919e3f299cfaa69a',
    messagingSenderId: '849620310895',
    projectId: 'muipzi',
    storageBucket: 'muipzi.firebasestorage.app',
    iosBundleId: 'com.example.muipzi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu4fYJL35nnfdA7K371tujICzUEmpvACc',
    appId: '1:849620310895:ios:e3e9d8919e3f299cfaa69a',
    messagingSenderId: '849620310895',
    projectId: 'muipzi',
    storageBucket: 'muipzi.firebasestorage.app',
    iosBundleId: 'com.example.muipzi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPh7JSoMyGuJyUar6mGOOyOwuA31Ld-IY',
    appId: '1:849620310895:web:ff363764f63fe9c2faa69a',
    messagingSenderId: '849620310895',
    projectId: 'muipzi',
    authDomain: 'muipzi.firebaseapp.com',
    storageBucket: 'muipzi.firebasestorage.app',
    measurementId: 'G-GGQWGFM1JK',
  );
}
